--------------------------------------------------------
--  File created - Tuesday-October-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View STP_CONTRACTOPERATION_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_CONTRACTOPERATION_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='CONTRACTOPERATION'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157112C00001$$" ON "BSMART_DATA"."STP_CONTRACTOPERATION_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_CONTRACTOPERATION_LK_IDX" ON "BSMART_DATA"."STP_CONTRACTOPERATION_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_CONTRACTOPERATION_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_CONTRACTOPERATION_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_DEFICIENCY_STATUS_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_DEFICIENCY_STATUS_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='INCORRECTLOCATION'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157162C00001$$" ON "BSMART_DATA"."STP_DEFICIENCY_STATUS_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_DEFICIENCY_STATUS_LK_IDX" ON "BSMART_DATA"."STP_DEFICIENCY_STATUS_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_DEFICIENCY_STATUS_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_DEFICIENCY_STATUS_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_PLANTSIZE_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_PLANTSIZE_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='PLANTSIZE'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157117C00001$$" ON "BSMART_DATA"."STP_PLANTSIZE_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_PLANTSIZE_LK_IDX" ON "BSMART_DATA"."STP_PLANTSIZE_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_PLANTSIZE_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_PLANTSIZE_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_SPECIES_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_SPECIES_LK" ("SPECIESID", "SPECIES", "COMMONNAME")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select SPECIESID, SPECIES, COMMONNAME from transd.fstspecies@etrans
;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_SPECIES_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_SPECIES_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_STOCKTYPE_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_STOCKTYPE_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='STOCKTYPE'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157120C00001$$" ON "BSMART_DATA"."STP_STOCKTYPE_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_STOCKTYPE_LK_IDX" ON "BSMART_DATA"."STP_STOCKTYPE_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_STOCKTYPE_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_STOCKTYPE_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_STUMPING_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_STUMPING_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='STUMPING'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157144C00001$$" ON "BSMART_DATA"."STP_STUMPING_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_STUMPING_LK_IDX" ON "BSMART_DATA"."STP_STUMPING_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_STUMPING_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_STUMPING_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_TAGCOLOR_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_TAGCOLOR_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(10), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value number path '$.code'))) as jt
WHERE COLUMN_NAME='TAGCOLOR'
;

  CREATE UNIQUE INDEX "BSMART_DATA"."SYS_IL0000157126C00001$$" ON "BSMART_DATA"."STP_TAGCOLOR_LK" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "BSMART_DATA"."STP_TAGCOLOR_LK_IDX" ON "BSMART_DATA"."STP_TAGCOLOR_LK" ("CODE_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" ;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_TAGCOLOR_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_TAGCOLOR_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_TREEHEALTH_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_TREEHEALTH_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(11), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value varchar2(10000) path '$.code'))) as jt
WHERE COLUMN_NAME='TREEHEALTH'
;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_TREEHEALTH_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_TREEHEALTH_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_TREEHEIGHT_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_TREEHEIGHT_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(11), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value varchar2(10000) path '$.code'))) as jt
WHERE COLUMN_NAME='TREEHEIGHT'
;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_TREEHEIGHT_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_TREEHEIGHT_LK';
--------------------------------------------------------
--  DDL for Materialized View STP_WARRANTYINSPECTIONTYPE_LK
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "BSMART_DATA"."STP_WARRANTYINSPECTIONTYPE_LK" ("CODE_NAME", "CODE_VALUE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BSMART_DATA" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select jt.CODE_NAME, jt.CODE_VALUE
from 
JSON_TABLE(stp_util_pkg.get_domain_json(11), '$.fields[*]' 
COLUMNS
   (column_name varchar2(10000) path '$.name',
    NESTED PATH '$.domain.codedValues[*]'
    COLUMNS
    (code_name varchar2(10000) path '$.name',
    code_value varchar2(10000) path '$.code'))) as jt
WHERE COLUMN_NAME='WARRANTYINSPECTIONTYPE'
;

   COMMENT ON MATERIALIZED VIEW "BSMART_DATA"."STP_WARRANTYINSPECTIONTYPE_LK"  IS 'snapshot table for snapshot BSMART_DATA.STP_WARRANTYINSPECTIONTYPE_LK';
